/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import ConexaoBanco.Conexao;
import Model.Livro;
import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class jf_livro_cadastro extends javax.swing.JInternalFrame {

    private Conexao conexao;

    /**
     * Creates new form jf_cadastro_livro
     */
    public jf_livro_cadastro() {
        this.conexao = new Conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo_livro_cad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_titulo_livro = new javax.swing.JTextField();
        txt_autores_livro = new javax.swing.JTextField();
        txt_edicao_livro = new javax.swing.JTextField();
        txt_editora_livro = new javax.swing.JTextField();
        salvar_livro = new javax.swing.JButton();
        txt_ano_livro = new javax.swing.JTextField();
        txt_isbn_livro = new javax.swing.JTextField();
        lb_isbn_livro = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Inclusão Livro");

        lb_titulo_livro_cad.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_titulo_livro_cad.setText("Título");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Autores");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Edição");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 25));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Ano");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Editora");
        jLabel5.setPreferredSize(new java.awt.Dimension(61, 50));

        txt_titulo_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_titulo_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_titulo_livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_titulo_livroFocusGained(evt);
            }
        });
        txt_titulo_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titulo_livroActionPerformed(evt);
            }
        });

        txt_autores_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_autores_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_edicao_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_edicao_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_editora_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_editora_livro.setMaximumSize(new java.awt.Dimension(600, 30));
        txt_editora_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        salvar_livro.setBackground(new java.awt.Color(51, 102, 255));
        salvar_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        salvar_livro.setForeground(new java.awt.Color(255, 255, 255));
        salvar_livro.setText("SALVAR");
        salvar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_livroActionPerformed(evt);
            }
        });

        txt_ano_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_ano_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_isbn_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        lb_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_isbn_livro.setText("ISBN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_editora_livro, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                .addComponent(txt_autores_livro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_titulo_livro_cad)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_isbn_livro)
                            .addComponent(txt_isbn_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(169, 169, 169))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvar_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo_livro_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_autores_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_editora_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_isbn_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_isbn_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(salvar_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        setBounds(100, 20, 738, 463);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_titulo_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titulo_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titulo_livroActionPerformed

    private void salvar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_livroActionPerformed
        // TODO add your handling code here:
         
        Livro book = new Livro();
        
        book.setTitulo(txt_titulo_livro.getText());
        book.setAutores(txt_autores_livro.getText());
        book.setEditora(txt_editora_livro.getText());
        book.setEdicao(Integer.parseInt(txt_edicao_livro.getText()));
        book.setAno(Integer.parseInt(txt_ano_livro.getText()));
        book.setIsbn(txt_isbn_livro.getText());
        
        Conexao c=null;
        //string com a consulta que será executada no banco
        
       String sql ="insert into livro (titulo,autores,editora,edicao,ano,isbn,disponibilidade)values('"+book.getTitulo()+"','"+book.getAutores()+"','"+book.getEditora()+"','"+String.valueOf(book.getEdicao())+"','"+String.valueOf(book.getAno())+"','"+book.getIsbn()+"',1)";
        
       
       try
        { 
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string
                
               
                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);
               
                sentenca.execute(); //executa o comando no banco
                sentenca.close(); //fecha a sentença
           
                
                this.conexao.getConnection().close(); //fecha a conexão com o banco
            }
            else {
                    String s = "ERRO";
                    JOptionPane.showMessageDialog(null, s);
                }
        }
        catch(SQLException ex)
        {
           throw new RuntimeException(ex);
        }
        
         // LIMPANDO AS CAIXA TXT APOS INSERIR NO BANCO
        txt_titulo_livro.setText("");
        txt_autores_livro.setText("");
        txt_editora_livro.setText("");
        txt_edicao_livro.setText("");
        txt_ano_livro.setText("");
        txt_isbn_livro.setText("");      
       
        
        //ALERTA DE SUCESSO
        String s = "SUCESSO";
        JOptionPane.showMessageDialog(null, s);
        
        
        
        
        
        
    }//GEN-LAST:event_salvar_livroActionPerformed

    private void txt_titulo_livroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_titulo_livroFocusGained
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt_titulo_livroFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_isbn_livro;
    private javax.swing.JLabel lb_titulo_livro_cad;
    private javax.swing.JButton salvar_livro;
    private javax.swing.JTextField txt_ano_livro;
    private javax.swing.JTextField txt_autores_livro;
    private javax.swing.JTextField txt_edicao_livro;
    private javax.swing.JTextField txt_editora_livro;
    private javax.swing.JTextField txt_isbn_livro;
    private javax.swing.JTextField txt_titulo_livro;
    // End of variables declaration//GEN-END:variables

    
}
