/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import ConexaoBanco.Conexao;
import Model.Livro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class jf_livro_alterar extends javax.swing.JInternalFrame {

    /**
     * Creates new form jf_alterar_livro
     */
    private Conexao conexao;
     String exemplar_pesquisa;
    
    public jf_livro_alterar() {
        this.conexao = new Conexao();
        initComponents();
        
        txt_ano_livro.setEditable(false);
        txt_autores_livro.setEditable(false);
        txt_edicao_livro.setEditable(false);
        txt_editora_livro.setEditable(false);
        txt_isbn_livro.setEditable(false);
        txt_titulo_livro.setEditable(false);
       btn_salvar_livro.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_exemplar_pesquisa_livro = new javax.swing.JLabel();
        txt_exemplar_pesquisa_livro = new javax.swing.JTextField();
        btn_pesquisar_livro = new javax.swing.JButton();
        lb_titulo_livro_alt = new javax.swing.JLabel();
        txt_ano_livro = new javax.swing.JTextField();
        txt_isbn_livro = new javax.swing.JTextField();
        lb_autores_livro_alt = new javax.swing.JLabel();
        lb_isbn_livro = new javax.swing.JLabel();
        lb_edicao_livro_alt = new javax.swing.JLabel();
        lb_ano_livro_alt = new javax.swing.JLabel();
        lb_editora_livro_alt = new javax.swing.JLabel();
        txt_titulo_livro = new javax.swing.JTextField();
        txt_autores_livro = new javax.swing.JTextField();
        txt_edicao_livro = new javax.swing.JTextField();
        txt_editora_livro = new javax.swing.JTextField();
        btn_salvar_livro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alterar Livro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_exemplar_pesquisa_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_exemplar_pesquisa_livro.setText("Exemplar");
        getContentPane().add(lb_exemplar_pesquisa_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        txt_exemplar_pesquisa_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_exemplar_pesquisa_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_exemplar_pesquisa_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, -1, 33));

        btn_pesquisar_livro.setBackground(new java.awt.Color(51, 102, 255));
        btn_pesquisar_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btn_pesquisar_livro.setForeground(new java.awt.Color(255, 255, 255));
        btn_pesquisar_livro.setText("Pesquisar");
        btn_pesquisar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisar_livroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pesquisar_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, -1, -1));

        lb_titulo_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_titulo_livro_alt.setText("Título");
        getContentPane().add(lb_titulo_livro_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        txt_ano_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_ano_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_ano_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 30));

        txt_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_isbn_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_isbn_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, 30));

        lb_autores_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_autores_livro_alt.setText("Autores");
        getContentPane().add(lb_autores_livro_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lb_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_isbn_livro.setText("ISBN");
        getContentPane().add(lb_isbn_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 32));

        lb_edicao_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_edicao_livro_alt.setText("Edição");
        lb_edicao_livro_alt.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(lb_edicao_livro_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, 32));

        lb_ano_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_ano_livro_alt.setText("Ano");
        getContentPane().add(lb_ano_livro_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        lb_editora_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_editora_livro_alt.setText("Editora");
        lb_editora_livro_alt.setPreferredSize(new java.awt.Dimension(61, 50));
        getContentPane().add(lb_editora_livro_alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 25));

        txt_titulo_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_titulo_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_titulo_livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_titulo_livroFocusGained(evt);
            }
        });
        txt_titulo_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titulo_livroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_titulo_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 30));

        txt_autores_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_autores_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_autores_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 600, 30));

        txt_edicao_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_edicao_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_edicao_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        txt_editora_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_editora_livro.setMaximumSize(new java.awt.Dimension(600, 30));
        txt_editora_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        getContentPane().add(txt_editora_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 600, 30));

        btn_salvar_livro.setBackground(new java.awt.Color(51, 102, 255));
        btn_salvar_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btn_salvar_livro.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar_livro.setText("SALVAR");
        btn_salvar_livro.setAlignmentX(0.5F);
        btn_salvar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_livroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar_livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 363, 281, 54));

        setBounds(60, 20, 869, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisar_livroActionPerformed
        // TODO add your handling code here:
                
    
         exemplar_pesquisa=txt_exemplar_pesquisa_livro.getText();
       
        
        Conexao c=null;
        
       
       
         try
        {   
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string
               
                 //prepara a sentença com a consulta da string
                String sql="select * from livro where isbn ='"+exemplar_pesquisa+"'";
                ResultSet resultado;
                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);
                
                resultado=sentenca.executeQuery(); //executa o comando no banco
                
                if (resultado.next()) {
                    txt_titulo_livro.setText(resultado.getString("titulo"));
                    txt_ano_livro.setText(resultado.getString("ano"));
                    txt_autores_livro.setText(resultado.getString("autores"));
                    txt_edicao_livro.setText(resultado.getString("edicao"));
                    txt_editora_livro.setText(resultado.getString("editora"));
                    txt_isbn_livro.setText(resultado.getString("isbn"));
                    
                    
                    
                    txt_ano_livro.setEditable(true);
                    txt_autores_livro.setEditable(true);
                    txt_edicao_livro.setEditable(true);
                    txt_editora_livro.setEditable(true);
                    txt_isbn_livro.setEditable(true);
                    txt_titulo_livro.setEditable(true);
                    btn_salvar_livro.setEnabled(true);
                    
                }
                else {
                    String s = "ERRO";
                    JOptionPane.showMessageDialog(null, s);
                }
                
                
                
                
               
                //txt_titulo_livro.setText(resultado.getString());
                
                //fecha a sentença
                sentenca.close();
                this.conexao.getConnection().close(); //fecha a conexão com o banco
                
                
            }
        }
        catch(SQLException ex)
        {
           throw new RuntimeException(ex);
        }
        
        
        
        
    }//GEN-LAST:event_btn_pesquisar_livroActionPerformed

    private void txt_titulo_livroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_titulo_livroFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_titulo_livroFocusGained

    private void txt_titulo_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titulo_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titulo_livroActionPerformed

    private void btn_salvar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_livroActionPerformed
        // TODO add your handling code here:

        Livro book = new Livro();

        book.setTitulo(txt_titulo_livro.getText());
        book.setAutores(txt_autores_livro.getText());
        book.setEditora(txt_editora_livro.getText());
        book.setEdicao(Integer.parseInt(txt_edicao_livro.getText()));
        book.setAno(Integer.parseInt(txt_ano_livro.getText()));
        book.setIsbn(txt_isbn_livro.getText());

        Conexao c=null;
        //string com a consulta que será executada no banco

        String sql ="update livro  set titulo = '"+book.getTitulo()+"',autores = '"+book.getAutores()+"',editora = '"+book.getEditora()+"', edicao = '"+ String.valueOf(book.getEdicao())+"',ano = '"+String.valueOf(book.getAno())+"',isbn = '"+book.getIsbn()+"' where exemplar ='"+exemplar_pesquisa+"'";                                                                                          
        
        try
        {
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string

                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);

                sentenca.execute(); //executa o comando no banco
                sentenca.close(); //fecha a sentença

                this.conexao.getConnection().close(); //fecha a conexão com o banco
            }
        }
        catch(SQLException ex)
        {
            throw new RuntimeException(ex);
        }

        // LIMPANDO AS CAIXA TXT APOS INSERIR NO BANCO
        txt_titulo_livro.setText("");
        txt_autores_livro.setText("");
        txt_editora_livro.setText("");
        txt_edicao_livro.setText("");
        txt_ano_livro.setText("");
        txt_exemplar_pesquisa_livro.setText("");
        txt_isbn_livro.setText("");
        
        txt_ano_livro.setEditable(false);
        txt_autores_livro.setEditable(false);
        txt_edicao_livro.setEditable(false);
        txt_editora_livro.setEditable(false);
        txt_isbn_livro.setEditable(false);
        txt_titulo_livro.setEditable(false);
        btn_salvar_livro.setEnabled(false);

        //ALERTA DE SUCESSO
        String s = "SUCESSO";
        JOptionPane.showMessageDialog(null, s);

    }//GEN-LAST:event_btn_salvar_livroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pesquisar_livro;
    private javax.swing.JButton btn_salvar_livro;
    private javax.swing.JLabel lb_ano_livro_alt;
    private javax.swing.JLabel lb_autores_livro_alt;
    private javax.swing.JLabel lb_edicao_livro_alt;
    private javax.swing.JLabel lb_editora_livro_alt;
    private javax.swing.JLabel lb_exemplar_pesquisa_livro;
    private javax.swing.JLabel lb_isbn_livro;
    private javax.swing.JLabel lb_titulo_livro_alt;
    private javax.swing.JTextField txt_ano_livro;
    private javax.swing.JTextField txt_autores_livro;
    private javax.swing.JTextField txt_edicao_livro;
    private javax.swing.JTextField txt_editora_livro;
    private javax.swing.JTextField txt_exemplar_pesquisa_livro;
    private javax.swing.JTextField txt_isbn_livro;
    private javax.swing.JTextField txt_titulo_livro;
    // End of variables declaration//GEN-END:variables
}
