/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import ConexaoBanco.Conexao;
import Model.Livro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class jf_livro_excluir extends javax.swing.JInternalFrame {

    /**
     * Creates new form jf_alterar_livro
     */
    private Conexao conexao;
     String isbn_pesquisa;
    
    public jf_livro_excluir() {
        this.conexao = new Conexao();
        initComponents();
        
        txt_ano_livro.setEditable(false);
        txt_autores_livro.setEditable(false);
        txt_edicao_livro.setEditable(false);
        txt_editora_livro.setEditable(false);
        txt_isbn_livro.setEditable(false);
        txt_titulo_livro.setEditable(false);
       btn_excluir_livro.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_isbn_pesquisa_livro_alt = new javax.swing.JLabel();
        txt_isbn_pesquisa_livro = new javax.swing.JTextField();
        btn_pesquisar_livro = new javax.swing.JButton();
        lb_titulo_livro_alt = new javax.swing.JLabel();
        txt_ano_livro = new javax.swing.JTextField();
        txt_isbn_livro = new javax.swing.JTextField();
        lb_autores_livro_alt = new javax.swing.JLabel();
        lb_isbn_livro = new javax.swing.JLabel();
        lb_edicao_livro_alt = new javax.swing.JLabel();
        lb_ano_livro_alt = new javax.swing.JLabel();
        lb_editora_livro_alt = new javax.swing.JLabel();
        txt_titulo_livro = new javax.swing.JTextField();
        txt_autores_livro = new javax.swing.JTextField();
        txt_edicao_livro = new javax.swing.JTextField();
        txt_editora_livro = new javax.swing.JTextField();
        btn_excluir_livro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Excluir Livro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lb_isbn_pesquisa_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_isbn_pesquisa_livro_alt.setText("ISBN");

        txt_isbn_pesquisa_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_isbn_pesquisa_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        btn_pesquisar_livro.setBackground(new java.awt.Color(51, 102, 255));
        btn_pesquisar_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btn_pesquisar_livro.setForeground(new java.awt.Color(255, 255, 255));
        btn_pesquisar_livro.setText("Pesquisar");
        btn_pesquisar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisar_livroActionPerformed(evt);
            }
        });

        lb_titulo_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_titulo_livro_alt.setText("Título");

        txt_ano_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_ano_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_isbn_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        lb_autores_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_autores_livro_alt.setText("Autores");

        lb_isbn_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_isbn_livro.setText("ISBN");

        lb_edicao_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_edicao_livro_alt.setText("Edição");
        lb_edicao_livro_alt.setPreferredSize(new java.awt.Dimension(140, 25));

        lb_ano_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_ano_livro_alt.setText("Ano");

        lb_editora_livro_alt.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_editora_livro_alt.setText("Editora");
        lb_editora_livro_alt.setPreferredSize(new java.awt.Dimension(61, 50));

        txt_titulo_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_titulo_livro.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_titulo_livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_titulo_livroFocusGained(evt);
            }
        });
        txt_titulo_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titulo_livroActionPerformed(evt);
            }
        });

        txt_autores_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_autores_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_edicao_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_edicao_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_editora_livro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_editora_livro.setMaximumSize(new java.awt.Dimension(600, 30));
        txt_editora_livro.setPreferredSize(new java.awt.Dimension(140, 25));

        btn_excluir_livro.setBackground(new java.awt.Color(255, 0, 0));
        btn_excluir_livro.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btn_excluir_livro.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir_livro.setText("EXCLUIR");
        btn_excluir_livro.setAlignmentX(0.5F);
        btn_excluir_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_livroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_edicao_livro_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97)
                                        .addComponent(lb_ano_livro_alt)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_isbn_livro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_isbn_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                        .addComponent(btn_excluir_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_editora_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_autores_livro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_editora_livro_alt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_titulo_livro_alt)
                            .addComponent(lb_autores_livro_alt)
                            .addComponent(lb_isbn_pesquisa_livro_alt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_isbn_pesquisa_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pesquisar_livro)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_isbn_pesquisa_livro_alt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_isbn_pesquisa_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisar_livro))
                .addGap(43, 43, 43)
                .addComponent(lb_titulo_livro_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_autores_livro_alt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_autores_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_editora_livro_alt, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_editora_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_edicao_livro_alt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(lb_ano_livro_alt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_isbn_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_isbn_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_excluir_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        setBounds(60, 20, 869, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisar_livroActionPerformed
        // TODO add your handling code here:
                
       
                isbn_pesquisa=txt_isbn_pesquisa_livro.getText();
        
        
        Conexao c=null;
        
       
       
         try
        {
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string
                String sql="select * from livro where isbn ='"+isbn_pesquisa+"'";
                ResultSet resultado;
                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);
                
                resultado=sentenca.executeQuery(); //executa o comando no banco
                
                if (resultado.next()) {
                    txt_titulo_livro.setText(resultado.getString("titulo"));
                    txt_ano_livro.setText(resultado.getString("ano"));
                    txt_autores_livro.setText(resultado.getString("autores"));
                    txt_edicao_livro.setText(resultado.getString("edicao"));
                    txt_editora_livro.setText(resultado.getString("editora"));
                    txt_isbn_livro.setText(resultado.getString("isbn"));
                    
                    
                    
                    
                    btn_excluir_livro.setEnabled(true);
                    
                }
                else {
                    String s = "ERRO";
                    JOptionPane.showMessageDialog(null, s);
                }
                
                
                
                
               
                //txt_titulo_livro.setText(resultado.getString());
                
                //fecha a sentença
                sentenca.close();
                this.conexao.getConnection().close(); //fecha a conexão com o banco
                
                
            }
        }
        catch(SQLException ex)
        {
           throw new RuntimeException(ex);
        }
        
        
        
        
    }//GEN-LAST:event_btn_pesquisar_livroActionPerformed

    private void txt_titulo_livroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_titulo_livroFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_titulo_livroFocusGained

    private void txt_titulo_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titulo_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titulo_livroActionPerformed

    private void btn_excluir_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_livroActionPerformed
        // TODO add your handling code here:

        Livro book = new Livro();

        book.setTitulo(txt_titulo_livro.getText());
        book.setAutores(txt_autores_livro.getText());
        book.setEditora(txt_editora_livro.getText());
        book.setEdicao(Integer.parseInt(txt_edicao_livro.getText()));
        book.setAno(Integer.parseInt(txt_ano_livro.getText()));
        book.setIsbn(txt_isbn_livro.getText());

        Conexao c=null;
        //string com a consulta que será executada no banco

        String sql ="delete from livro where isbn ='"+isbn_pesquisa+"'";                                                                                          
        
        try
        {
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string

                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);

                sentenca.execute(); //executa o comando no banco
                sentenca.close(); //fecha a sentença

                this.conexao.getConnection().close(); //fecha a conexão com o banco
                
                
                // LIMPANDO AS CAIXA TXT APOS INSERIR NO BANCO
        txt_titulo_livro.setText("");
        txt_autores_livro.setText("");
        txt_editora_livro.setText("");
        txt_edicao_livro.setText("");
        txt_ano_livro.setText("");
        txt_isbn_pesquisa_livro.setText("");
        txt_isbn_livro.setText("");
        
     

        //ALERTA DE SUCESSO
        String s = "SUCESSO";
        JOptionPane.showMessageDialog(null, s);
            }
        }
        catch(SQLException ex)
        {
            throw new RuntimeException(ex);
        }

        

    }//GEN-LAST:event_btn_excluir_livroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_excluir_livro;
    private javax.swing.JButton btn_pesquisar_livro;
    private javax.swing.JLabel lb_ano_livro_alt;
    private javax.swing.JLabel lb_autores_livro_alt;
    private javax.swing.JLabel lb_edicao_livro_alt;
    private javax.swing.JLabel lb_editora_livro_alt;
    private javax.swing.JLabel lb_isbn_livro;
    private javax.swing.JLabel lb_isbn_pesquisa_livro_alt;
    private javax.swing.JLabel lb_titulo_livro_alt;
    private javax.swing.JTextField txt_ano_livro;
    private javax.swing.JTextField txt_autores_livro;
    private javax.swing.JTextField txt_edicao_livro;
    private javax.swing.JTextField txt_editora_livro;
    private javax.swing.JTextField txt_isbn_livro;
    private javax.swing.JTextField txt_isbn_pesquisa_livro;
    private javax.swing.JTextField txt_titulo_livro;
    // End of variables declaration//GEN-END:variables
}
