/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author guilh
 */
public class jf_tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form jf_tela_principal
     */
    public jf_tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_tela_principal = new javax.swing.JDesktopPane();
        menu_principal = new javax.swing.JMenuBar();
        livros_menu = new javax.swing.JMenu();
        incluir_livros = new javax.swing.JMenuItem();
        alterar_livros = new javax.swing.JMenuItem();
        excluir_livros = new javax.swing.JMenuItem();
        listar_livros = new javax.swing.JMenuItem();
        buscar_isbn_livros = new javax.swing.JMenuItem();
        buscar_titulo_livros = new javax.swing.JMenuItem();
        buscar_editora_livros = new javax.swing.JMenuItem();
        usuarios_menu = new javax.swing.JMenu();
        incluir_usuario = new javax.swing.JMenuItem();
        alterar_usuario = new javax.swing.JMenuItem();
        excluir_usuario = new javax.swing.JMenuItem();
        listar_usuario = new javax.swing.JMenuItem();
        buscar_nome_usuario = new javax.swing.JMenuItem();
        buscar_login_usuario = new javax.swing.JMenuItem();
        emprestimo = new javax.swing.JMenu();
        emprestimo_incluir = new javax.swing.JMenuItem();
        emprestimo_renovar = new javax.swing.JMenuItem();
        emprestimo_devolucao = new javax.swing.JMenuItem();
        emprestimos_buscar_isbn = new javax.swing.JMenuItem();
        emprestimo_buscar_titulo = new javax.swing.JMenuItem();
        emprestimo_buscar_user = new javax.swing.JMenuItem();
        emprestimo_listar = new javax.swing.JMenuItem();
        reservas = new javax.swing.JMenu();
        reserva_realizar = new javax.swing.JMenuItem();
        reservar_cancelar = new javax.swing.JMenuItem();
        multas = new javax.swing.JMenu();
        multa_pagar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISB - Tela Principal");

        javax.swing.GroupLayout painel_tela_principalLayout = new javax.swing.GroupLayout(painel_tela_principal);
        painel_tela_principal.setLayout(painel_tela_principalLayout);
        painel_tela_principalLayout.setHorizontalGroup(
            painel_tela_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1512, Short.MAX_VALUE)
        );
        painel_tela_principalLayout.setVerticalGroup(
            painel_tela_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        menu_principal.setMaximumSize(new java.awt.Dimension(300, 32768));

        livros_menu.setText("Livros");
        livros_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livros_menuActionPerformed(evt);
            }
        });

        incluir_livros.setText("Incluir");
        incluir_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluir_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(incluir_livros);

        alterar_livros.setText("Alterar");
        alterar_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(alterar_livros);

        excluir_livros.setText("Excluir");
        excluir_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(excluir_livros);

        listar_livros.setText("Listar");
        listar_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(listar_livros);

        buscar_isbn_livros.setText("Buscar ISBN");
        buscar_isbn_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_isbn_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(buscar_isbn_livros);

        buscar_titulo_livros.setText("Buscar Título");
        buscar_titulo_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_titulo_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(buscar_titulo_livros);

        buscar_editora_livros.setText("Buscar por Editora");
        buscar_editora_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_editora_livrosActionPerformed(evt);
            }
        });
        livros_menu.add(buscar_editora_livros);

        menu_principal.add(livros_menu);

        usuarios_menu.setText("Usuários");
        usuarios_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarios_menuActionPerformed(evt);
            }
        });

        incluir_usuario.setText("Incluir");
        incluir_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluir_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(incluir_usuario);

        alterar_usuario.setText("Alterar");
        alterar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(alterar_usuario);

        excluir_usuario.setText("Excluir");
        excluir_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(excluir_usuario);

        listar_usuario.setText("Listar");
        listar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(listar_usuario);

        buscar_nome_usuario.setText("Buscar por Nome");
        buscar_nome_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_nome_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(buscar_nome_usuario);

        buscar_login_usuario.setText("Buscar por Login");
        buscar_login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_login_usuarioActionPerformed(evt);
            }
        });
        usuarios_menu.add(buscar_login_usuario);

        menu_principal.add(usuarios_menu);

        emprestimo.setText("Emprestimos");

        emprestimo_incluir.setText("Realizar emprestimo");
        emprestimo_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_incluirActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_incluir);

        emprestimo_renovar.setText("Renovar emprestimo");
        emprestimo_renovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_renovarActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_renovar);

        emprestimo_devolucao.setText("Devolução");
        emprestimo_devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_devolucaoActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_devolucao);

        emprestimos_buscar_isbn.setText("Buscar emprestimo ISBN");
        emprestimos_buscar_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimos_buscar_isbnActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimos_buscar_isbn);

        emprestimo_buscar_titulo.setText("Buscar emprestimo Título");
        emprestimo_buscar_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_buscar_tituloActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_buscar_titulo);

        emprestimo_buscar_user.setText("Buscar emprestimo Usuário");
        emprestimo_buscar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_buscar_userActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_buscar_user);

        emprestimo_listar.setText("Listar");
        emprestimo_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimo_listarActionPerformed(evt);
            }
        });
        emprestimo.add(emprestimo_listar);

        menu_principal.add(emprestimo);

        reservas.setText("Reservas");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });

        reserva_realizar.setText("Realizar reserva");
        reserva_realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserva_realizarActionPerformed(evt);
            }
        });
        reservas.add(reserva_realizar);

        reservar_cancelar.setText("Cancelar reserva");
        reservar_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar_cancelarActionPerformed(evt);
            }
        });
        reservas.add(reservar_cancelar);

        menu_principal.add(reservas);

        multas.setText("Multas");

        multa_pagar.setText("Pagar multa");
        multas.add(multa_pagar);

        menu_principal.add(multas);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_tela_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_tela_principal)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterar_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_livrosActionPerformed
            // TODO add your handling code here:]
        jf_livro_alterar obj = new jf_livro_alterar();
        painel_tela_principal.add(obj);
        
        obj.setVisible(true);  
        
    }//GEN-LAST:event_alterar_livrosActionPerformed

    private void excluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_usuarioActionPerformed
        // TODO add your handling code here:
        
        
         jf_usuario_excluir obj = new jf_usuario_excluir();
        painel_tela_principal.add(obj);
        
        obj.setVisible(true); 
    }//GEN-LAST:event_excluir_usuarioActionPerformed

    private void incluir_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluir_livrosActionPerformed
        // TODO add your handling code here:
        jf_livro_cadastro obj = new jf_livro_cadastro();
        painel_tela_principal.add(obj);
        obj.setVisible(true);
        
    }//GEN-LAST:event_incluir_livrosActionPerformed

    private void usuarios_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarios_menuActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_usuarios_menuActionPerformed

    private void alterar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_usuarioActionPerformed
        // TODO add your handling code here:
        jf_usuario_alterar obj = new jf_usuario_alterar();
        painel_tela_principal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_alterar_usuarioActionPerformed

    private void incluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluir_usuarioActionPerformed
        // TODO add your handling code here:
        jf_usuario_cadastro obj_user = new jf_usuario_cadastro();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_incluir_usuarioActionPerformed

    private void excluir_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_livrosActionPerformed
        // TODO add your handling code here:
        
        jf_livro_excluir obj_user = new jf_livro_excluir();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_excluir_livrosActionPerformed

    private void listar_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_livrosActionPerformed
        // TODO add your handling code here:
        
        jf_livro_listar obj_user = new jf_livro_listar();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_listar_livrosActionPerformed

    private void buscar_isbn_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_isbn_livrosActionPerformed
        // TODO add your handling code here:
        jf_livro_buscar_isbn obj_user = new jf_livro_buscar_isbn();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_buscar_isbn_livrosActionPerformed

    private void buscar_titulo_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_titulo_livrosActionPerformed
        // TODO add your handling code here:
        jf_livro_buscar_titulo obj_user = new jf_livro_buscar_titulo();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_buscar_titulo_livrosActionPerformed

    private void buscar_editora_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_editora_livrosActionPerformed
        // TODO add your handling code here:
        jf_livro_buscar_editora obj_user = new jf_livro_buscar_editora();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_buscar_editora_livrosActionPerformed

    private void listar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_usuarioActionPerformed
        // TODO add your handling code here:
        
        jf_usuario_listar obj_user = new jf_usuario_listar();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
        
    }//GEN-LAST:event_listar_usuarioActionPerformed

    private void buscar_nome_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_nome_usuarioActionPerformed
        // TODO add your handling code here:
        
        jf_usuario_buscar_nome obj_user = new jf_usuario_buscar_nome();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
    }//GEN-LAST:event_buscar_nome_usuarioActionPerformed

    private void buscar_login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_login_usuarioActionPerformed
        // TODO add your handling code here:
        jf_usuario_buscar_login obj_user = new jf_usuario_buscar_login();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
    }//GEN-LAST:event_buscar_login_usuarioActionPerformed

    private void emprestimo_devolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_devolucaoActionPerformed
        // TODO add your handling code here:
        jf_emprestimo_devolucao obj_user = new jf_emprestimo_devolucao();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_emprestimo_devolucaoActionPerformed

    private void emprestimo_buscar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_buscar_userActionPerformed
        // TODO add your handling code here:
        
         jf_emprestimo_buscar_usuario obj_user = new jf_emprestimo_buscar_usuario();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_emprestimo_buscar_userActionPerformed

    private void emprestimo_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_incluirActionPerformed
        // TODO add your handling code here:
        jf_emprestimo obj_user = new jf_emprestimo();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
        
    }//GEN-LAST:event_emprestimo_incluirActionPerformed

    private void emprestimo_renovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_renovarActionPerformed
        // TODO add your handling code here:
        jf_emprestimo_renovacao obj_user = new jf_emprestimo_renovacao();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
    }//GEN-LAST:event_emprestimo_renovarActionPerformed

    private void emprestimo_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_listarActionPerformed
        // TODO add your handling code here:
        
        jf_emprestimo_listar obj_user = new jf_emprestimo_listar();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
    }//GEN-LAST:event_emprestimo_listarActionPerformed

    private void emprestimo_buscar_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimo_buscar_tituloActionPerformed
        // TODO add your handling code here:
        jf_emprestimo_buscar_titulo obj_user = new jf_emprestimo_buscar_titulo();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
    }//GEN-LAST:event_emprestimo_buscar_tituloActionPerformed

    private void reservar_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar_cancelarActionPerformed
        // TODO add your handling code here:
        
         jf_reserva_cancelar obj_user = new jf_reserva_cancelar();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
    }//GEN-LAST:event_reservar_cancelarActionPerformed

    private void emprestimos_buscar_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimos_buscar_isbnActionPerformed
        // TODO add your handling code here:
        
        jf_emprestimo_buscar_isbn obj_user = new jf_emprestimo_buscar_isbn();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
                
    }//GEN-LAST:event_emprestimos_buscar_isbnActionPerformed

    private void reserva_realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserva_realizarActionPerformed
        // TODO add your handling code here:
        jf_reserva obj_user = new jf_reserva();
        painel_tela_principal.add(obj_user);
        obj_user.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_reserva_realizarActionPerformed

    private void livros_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livros_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livros_menuActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterar_livros;
    private javax.swing.JMenuItem alterar_usuario;
    private javax.swing.JMenuItem buscar_editora_livros;
    private javax.swing.JMenuItem buscar_isbn_livros;
    private javax.swing.JMenuItem buscar_login_usuario;
    private javax.swing.JMenuItem buscar_nome_usuario;
    private javax.swing.JMenuItem buscar_titulo_livros;
    private javax.swing.JMenu emprestimo;
    private javax.swing.JMenuItem emprestimo_buscar_titulo;
    private javax.swing.JMenuItem emprestimo_buscar_user;
    private javax.swing.JMenuItem emprestimo_devolucao;
    private javax.swing.JMenuItem emprestimo_incluir;
    private javax.swing.JMenuItem emprestimo_listar;
    private javax.swing.JMenuItem emprestimo_renovar;
    private javax.swing.JMenuItem emprestimos_buscar_isbn;
    private javax.swing.JMenuItem excluir_livros;
    private javax.swing.JMenuItem excluir_usuario;
    private javax.swing.JMenuItem incluir_livros;
    private javax.swing.JMenuItem incluir_usuario;
    private javax.swing.JMenuItem listar_livros;
    private javax.swing.JMenuItem listar_usuario;
    private javax.swing.JMenu livros_menu;
    private javax.swing.JMenuBar menu_principal;
    private javax.swing.JMenuItem multa_pagar;
    private javax.swing.JMenu multas;
    private javax.swing.JDesktopPane painel_tela_principal;
    private javax.swing.JMenuItem reserva_realizar;
    private javax.swing.JMenuItem reservar_cancelar;
    private javax.swing.JMenu reservas;
    private javax.swing.JMenu usuarios_menu;
    // End of variables declaration//GEN-END:variables
}
