/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import ConexaoBanco.Conexao;
import Model.Usuario;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class jf_usuario_cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form jf_cadastro_livro
     */
    private Conexao conexao;
    public jf_usuario_cadastro() {
        this.conexao = new Conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nome_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_endereco_usuario = new javax.swing.JLabel();
        lb_estado_usuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_cidade_usuario = new javax.swing.JLabel();
        txt_nome_usuario = new javax.swing.JTextField();
        txt_endereco_usuario = new javax.swing.JTextField();
        txt_estado_usuario = new javax.swing.JTextField();
        txt_cidade_usuario = new javax.swing.JTextField();
        btn_salvar_usuario = new javax.swing.JButton();
        txt_nascimento_usuario = new javax.swing.JTextField();
        lb_nascimento_usuario = new javax.swing.JLabel();
        txt_numero_usuario = new javax.swing.JTextField();
        lb_cpf_usuario = new javax.swing.JLabel();
        txt_cpf_usuario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Inclusão Usuário");

        lb_nome_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_nome_usuario.setText("Nome");

        lb_endereco_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_endereco_usuario.setText("Endereço");

        lb_estado_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_estado_usuario.setText("Estado");
        lb_estado_usuario.setPreferredSize(new java.awt.Dimension(140, 25));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Número");

        lb_cidade_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_cidade_usuario.setText("Cidade");
        lb_cidade_usuario.setPreferredSize(new java.awt.Dimension(61, 50));

        txt_nome_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_nome_usuario.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_nome_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nome_usuarioFocusGained(evt);
            }
        });
        txt_nome_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_usuarioActionPerformed(evt);
            }
        });

        txt_endereco_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_endereco_usuario.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_estado_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_estado_usuario.setPreferredSize(new java.awt.Dimension(140, 25));

        txt_cidade_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_cidade_usuario.setMaximumSize(new java.awt.Dimension(600, 30));
        txt_cidade_usuario.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_cidade_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidade_usuarioActionPerformed(evt);
            }
        });

        btn_salvar_usuario.setBackground(new java.awt.Color(51, 102, 255));
        btn_salvar_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btn_salvar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar_usuario.setText("SALVAR");
        btn_salvar_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salvar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_usuarioActionPerformed(evt);
            }
        });

        txt_nascimento_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_nascimento_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nascimento_usuarioActionPerformed(evt);
            }
        });

        lb_nascimento_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_nascimento_usuario.setText("Data Nascimento");
        lb_nascimento_usuario.setPreferredSize(new java.awt.Dimension(61, 50));

        txt_numero_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_numero_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numero_usuarioActionPerformed(evt);
            }
        });

        lb_cpf_usuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lb_cpf_usuario.setText("CPF");
        lb_cpf_usuario.setPreferredSize(new java.awt.Dimension(61, 50));

        txt_cpf_usuario.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_cpf_usuario.setMaximumSize(new java.awt.Dimension(600, 30));
        txt_cpf_usuario.setPreferredSize(new java.awt.Dimension(140, 25));
        txt_cpf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nascimento_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nascimento_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nome_usuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_endereco_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_endereco_usuario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_cidade_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cidade_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_estado_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lb_estado_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numero_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salvar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lb_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_nascimento_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nascimento_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_endereco_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_endereco_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_cidade_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(txt_cidade_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(2, 2, 2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_estado_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_estado_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_numero_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salvar_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        setBounds(100, 20, 809, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nome_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_usuarioActionPerformed

    private void btn_salvar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_usuarioActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        
        Usuario user = new Usuario();
        
        //faz a atribuição dos campos da tela para o objeto
        
        user.setNome(txt_nome_usuario.getText());
         
        user.setCpf(txt_cpf_usuario.getText());
      
        
        user.setNascimento(txt_nascimento_usuario.getText());
       
        
        user.setEndereco(txt_endereco_usuario.getText());
        user.setCidade(txt_cidade_usuario.getText());
        user.setEstado(txt_estado_usuario.getText());
      
        user.setNumero(Integer.parseInt(txt_numero_usuario.getText()));
            
        
       
        Conexao c=null;
        //string com a consulta que será executada no banco
        
        String sql ="insert into usuario (nome,cpf,nascimento,endereco,cidade,estado,numero)values('"+user.getNome()+"','"+user.getCpf()+"','"+user.getNascimento()+"','"+user.getEndereco()+"','"+user.getCidade()+"','"+user.getEstado()+"','"+String.valueOf(user.getNumero())+"')";
        System.out.println(sql);
        
        try
        {
            //tenta realizar a conexão, se retornar verdadeiro entra no IF
            if(this.conexao.conectar())
            {
                //prepara a sentença com a consulta da string
                
               
                PreparedStatement sentenca = this.conexao.getConnection().prepareStatement(sql);
                
                sentenca.execute(); //executa o comando no banco
                sentenca.close(); //fecha a sentença
                
                
                this.conexao.getConnection().close(); //fecha a conexão com o banco
            }
            else {
                    String s = "ERRO";
                    JOptionPane.showMessageDialog(null, s);
                }
        }
        catch(SQLException ex)
        {
           throw new RuntimeException(ex);
        }
        
        // LIMPANDO AS CAIXA TXT APOS INSERIR NO BANCO
        txt_nome_usuario.setText("");
        txt_cpf_usuario.setText("");
        txt_nascimento_usuario.setText("");
        txt_endereco_usuario.setText("");
        txt_cidade_usuario.setText("");
        txt_estado_usuario.setText("");      
        txt_numero_usuario.setText("");
        
        //ALERTA DE SUCESSO
        String s = "SUCESSO";
        JOptionPane.showMessageDialog(null, s);
        
        
    }//GEN-LAST:event_btn_salvar_usuarioActionPerformed

    private void txt_nome_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nome_usuarioFocusGained
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt_nome_usuarioFocusGained

    private void txt_nascimento_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nascimento_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nascimento_usuarioActionPerformed

    private void txt_numero_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numero_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numero_usuarioActionPerformed

    private void txt_cpf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf_usuarioActionPerformed

    private void txt_cidade_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidade_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidade_usuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_cidade_usuario;
    private javax.swing.JLabel lb_cpf_usuario;
    private javax.swing.JLabel lb_endereco_usuario;
    private javax.swing.JLabel lb_estado_usuario;
    private javax.swing.JLabel lb_nascimento_usuario;
    private javax.swing.JLabel lb_nome_usuario;
    private javax.swing.JTextField txt_cidade_usuario;
    private javax.swing.JTextField txt_cpf_usuario;
    private javax.swing.JTextField txt_endereco_usuario;
    private javax.swing.JTextField txt_estado_usuario;
    private javax.swing.JTextField txt_nascimento_usuario;
    private javax.swing.JTextField txt_nome_usuario;
    private javax.swing.JTextField txt_numero_usuario;
    // End of variables declaration//GEN-END:variables
}
